application: urfatu-tw-weibo
version: 1
runtime: python
api_version: 1

handlers:
- url: /twitter(.*)
  script: twitter.py

- url: /binding.html
  static_files: static/binding.html
  upload: static/binding.html

- url: /_ah/xmpp/message/chat/
  script: weibo_chat.py

- url: .*
  script : app.py

inbound_services:
- xmpp_message

