application: urfatu-tw-weibo
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: "latest"

handlers:
- url: /twitter(.*)
  script: twitter.py

- url: /binding.html
  static_files: static/binding.html
  upload: static/binding.html

- url: /_ah/xmpp/message/chat/
  script: weibo_chat.app

- url: .*
  script : app.app

inbound_services:
- xmpp_message


